/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'bed' : null } |
  { 'sofa' : null } |
  { 'mediaUnit' : null } |
  { 'diningTable' : null };
export type Material = { 'matteWalnut' : null } |
  { 'naturalTeak' : null } |
  { 'charcoalAsh' : null };
export interface Product {
  'id' : string,
  'availableMaterials' : Array<Material>,
  'name' : string,
  'room' : Room,
  'isNewArrival' : boolean,
  'description' : string,
  'category' : Category,
  'availableUpholstery' : Array<Upholstery>,
  'priceInr' : bigint,
}
export type Room = { 'bedroom' : null } |
  { 'dining' : null } |
  { 'living' : null };
export interface ShowroomLead {
  'id' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
  'pincode' : string,
}
export type Upholstery = { 'italianVelvet' : null } |
  { 'performanceBoucle' : null };
export interface _SERVICE {
  'getMostLoved' : ActorMethod<[bigint], Array<Product>>,
  'getNewArrivals' : ActorMethod<[], Array<Product>>,
  'getProductById' : ActorMethod<[string], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByMaterial' : ActorMethod<[string], Array<Product>>,
  'getProductsByRoom' : ActorMethod<[string], Array<Product>>,
  'getShowroomLeads' : ActorMethod<[], Array<ShowroomLead>>,
  'recordView' : ActorMethod<[string], undefined>,
  'submitShowroomLead' : ActorMethod<
    [string, string, string, string, string],
    string
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];