/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Material = IDL.Variant({
  'matteWalnut' : IDL.Null,
  'naturalTeak' : IDL.Null,
  'charcoalAsh' : IDL.Null,
});
export const Room = IDL.Variant({
  'bedroom' : IDL.Null,
  'dining' : IDL.Null,
  'living' : IDL.Null,
});
export const Category = IDL.Variant({
  'bed' : IDL.Null,
  'sofa' : IDL.Null,
  'mediaUnit' : IDL.Null,
  'diningTable' : IDL.Null,
});
export const Upholstery = IDL.Variant({
  'italianVelvet' : IDL.Null,
  'performanceBoucle' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'availableMaterials' : IDL.Vec(Material),
  'name' : IDL.Text,
  'room' : Room,
  'isNewArrival' : IDL.Bool,
  'description' : IDL.Text,
  'category' : Category,
  'availableUpholstery' : IDL.Vec(Upholstery),
  'priceInr' : IDL.Nat,
});
export const ShowroomLead = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
});

export const idlService = IDL.Service({
  'getMostLoved' : IDL.Func([IDL.Nat], [IDL.Vec(Product)], ['query']),
  'getNewArrivals' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductById' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByMaterial' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getProductsByRoom' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getShowroomLeads' : IDL.Func([], [IDL.Vec(ShowroomLead)], ['query']),
  'recordView' : IDL.Func([IDL.Text], [], []),
  'submitShowroomLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Material = IDL.Variant({
    'matteWalnut' : IDL.Null,
    'naturalTeak' : IDL.Null,
    'charcoalAsh' : IDL.Null,
  });
  const Room = IDL.Variant({
    'bedroom' : IDL.Null,
    'dining' : IDL.Null,
    'living' : IDL.Null,
  });
  const Category = IDL.Variant({
    'bed' : IDL.Null,
    'sofa' : IDL.Null,
    'mediaUnit' : IDL.Null,
    'diningTable' : IDL.Null,
  });
  const Upholstery = IDL.Variant({
    'italianVelvet' : IDL.Null,
    'performanceBoucle' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'availableMaterials' : IDL.Vec(Material),
    'name' : IDL.Text,
    'room' : Room,
    'isNewArrival' : IDL.Bool,
    'description' : IDL.Text,
    'category' : Category,
    'availableUpholstery' : IDL.Vec(Upholstery),
    'priceInr' : IDL.Nat,
  });
  const ShowroomLead = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
  });
  
  return IDL.Service({
    'getMostLoved' : IDL.Func([IDL.Nat], [IDL.Vec(Product)], ['query']),
    'getNewArrivals' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductById' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByMaterial' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsByRoom' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'getShowroomLeads' : IDL.Func([], [IDL.Vec(ShowroomLead)], ['query']),
    'recordView' : IDL.Func([IDL.Text], [], []),
    'submitShowroomLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };